apiVersion: v1
kind: Service
metadata:
  name: react-ui-service
spec:
  type: NodePort
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: 80          # inside cluster
      targetPort: 80    # container port
      nodePort: 30080   # exposed port on all cluster nodes

